[package]
name = "rust_lambda_hello"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.140"
log = "0.4.27"