name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main  # Chỉ đồng bộ khi có push lên nhánh main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Bỏ shallow clone, giúp push toàn bộ commit lịch sử

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/hbao1411/bao-project.git
          git push --mirror gitlab
