name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main  # Chỉ đồng bộ khi push lên nhánh main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/hbao1411/bao-project.git
          git push --mirror gitlab
